models:
  User:
    table: users
    fields:
      id:
        type: integer
        primaryKey: true
        autoIncrement: true
      email:
        type: string
        unique: true
        nullable: false
      username:
        type: string
        unique: true
        nullable: false
      password:
        type: string
        nullable: false
      createdAt:
        type: timestamp
        default: now

  Food:
    table: foods
    fields:
      id:
        type: integer
        primaryKey: true
        autoIncrement: true
      name:
        type: string
        nullable: false
      category:
        type: string
        nullable: false

  UserFood:
    table: user_food
    primaryKey: [userId, foodId]
    fields:
      userId:
        type: integer
        nullable: false
        references:
          table: users
          column: id
          onDelete: CASCADE
      foodId:
        type: integer
        nullable: false
        references:
          table: foods
          column: id
          onDelete: CASCADE
