models:
  User:
    table: users
    fields:
      id:
        type: integer
        primaryKey: true
        autoIncrement: true
      email:
        type: string
        unique: true
        nullable: false
        maxLength: 255
      username:
        type: string
        unique: true
        nullable: false
        maxLength: 50
      password:
        type: string
        nullable: false
      createdAt:
        type: timestamp
        default: now
    indexes:
      - fields: [email]
      - fields: [username]
